name: Build and Push Docker Image

on:
  push:
    branches:
      - guestbook-image

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List directory contents
      run: ls -la

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: List directory contents
      run: ls -la
 
    - name: List directory contents
      run: pwd

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go -f guestbook-go/Dockerfile .

    - name: Push the Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/guestbook-go
