name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # The virtual environment to run the job

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sanlogu22
          password: dckr_pat_QVB5A3REiY3IdO08emYwI8Pzvko

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sanlogu22/guestbook:${{ github.sha }}
